# List of source directories to backup.
source_directories:
    - ~/Developer/Espalada
    - ~/Developer/42workbase
    - ~/.config
    - ~/.ssh

# Paths of local or remote repositories to backup to.
repositories:
    - path: ${BORG_REPO}
      label: MacBook on BorgBase

exclude_patterns:
    - '*.pyc'
    - ~/*/.cache
    - .DS_Store

encryption_passphrase: ${BORG_PASSPHRASE}
compression: auto,zstd
archive_name_format: '{hostname}-{now:%Y-%m-%d-%H%M%S}'

retries: 5
retry_wait: 5

# Retention policy for how many backups to keep.
keep_daily: 3
keep_weekly: 4
keep_monthly: 12

skip_actions:
    - check

check_last: 3

commands:
    - before: action
      when: [create]
      run:
          - echo "`date` - Starting backup"
    - after: action
      when: [create]
      run:
          - echo "`date` - Finished backup"
